### ISSUE TITLE
bug(Table): incorrect display of fixed table columns when visible false

### ISSUE THREAD

**Issue by Dimasikkk1** [dotnetcore/BootstrapBlazor#3062] opened 2024-03-13 11:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I found that when you hide the first column of the table, then the remaining fixed columns are incorrectly displayed, somewhere in their place there is a void. Sometimes the last fixed column jumped to the zero place, and there was a void in its place, but I have not yet figured out how to reproduce this, just when hiding the first column.

![image](https://github.com/dotnetcore/BootstrapBlazor/assets/31472338/4d709421-2f6c-4b1f-8269-396d9735e0be)

### Expected Behavior

Fixed columns in their places.

### Steps To Reproduce

Test repo: [https://github.com/Dimasikkk1/MP1TestRepo](https://github.com/Dimasikkk1/MP1TestRepo) 

### .NET Version

8.0.200-preview.23624.5

### Anything else?

ASP.Net Core 8
Visual Studio Community 2022 17.9.0 Preview 4.0

ПАКЕТ SDK ДЛЯ .NET:
 Version:           8.0.200-preview.23624.5
 Commit:            8065b9770c
 Workload version:  8.0.200-manifests.66f5ce51

Среда выполнения:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.200-preview.23624.5\

Установленные рабочие нагрузки .NET:
 Workload version: 8.0.200-manifests.66f5ce51
 [maui-windows]
   Источник установки: VS 17.9.34518.117
   Версия манифеста:    8.0.3/8.0.100
   Путь к манифесту:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.3\WorkloadManifest.json
   Тип установки:              Msi

 [ios]
   Источник установки: VS 17.9.34518.117
   Версия манифеста:    17.2.8004/8.0.100
   Путь к манифесту:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.ios\17.2.8004\WorkloadManifest.json
   Тип установки:              Msi

 [maccatalyst]
   Источник установки: VS 17.9.34518.117
   Версия манифеста:    17.2.8004/8.0.100
   Путь к манифесту:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maccatalyst\17.2.8004\WorkloadManifest.json
   Тип установки:              Msi

 [android]
   Источник установки: VS 17.9.34518.117
   Версия манифеста:    34.0.52/8.0.100
   Путь к манифесту:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.android\34.0.52\WorkloadManifest.json
   Тип установки:              Msi

Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71

.NET SDKs installed:
  8.0.100-rc.1.23463.5 [C:\Program Files\dotnet\sdk]
  8.0.200-preview.23624.5 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-rc.1.23421.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-rc.1.23419.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-rc.1.23420.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

**Comment by ArgoZhang** [comment] 2024-03-14 01:01
@Dimasikkk1 thanks this is a bug. will be fixed in the next release

**Comment by ArgoZhang** [comment] 2024-03-15 04:56
@Dimasikkk1 fixed

![image](https://github.com/dotnetcore/BootstrapBlazor/assets/22001478/9f2f6af9-2372-47a4-a3c5-001980ed5a22)

update your stylesheet

**Comment by Dimasikkk1** [comment] 2024-03-15 13:21
I updated the package to version 8.3.4-beta04, and when I hide the first two columns, there is a void in place of the first column. You can check on the same mini repository.

**Comment by Dimasikkk1** [comment] 2024-03-17 06:42
I have updated the package to version 8.3.4 and my test repository, which is listed above. If all columns visible is true, some is hidden anyway. This is also a problem when you hide some columns.

![image](https://github.com/dotnetcore/BootstrapBlazor/assets/31472338/cd831d3e-58aa-4b8f-9ffb-8d2ff4bccd01)

**Comment by ArgoZhang** [comment] 2024-03-17 06:59
@Dimasikkk1 hi. I think this is caused by inappropriate settings. Not all columns can be fixed, as that would be meaningless. If the last column is not a fixed column, then the preceding column cannot be fixed either. Currently, this is by design.

the below code will be work fine.

```
<TableColumn @bind-Field="context.Column1" Fixed="true" Width="160" />
<TableColumn @bind-Field="context.Column2" Fixed="true" Width="160" />
<TableColumn @bind-Field="context.Column3" Fixed="true" Width="160" />
<TableColumn @bind-Field="context.Column4" Fixed="false" Width="160" />
<TableColumn @bind-Field="context.Column5" Fixed="false" Width="160" />
<TableColumn @bind-Field="context.Column6" Fixed="false" Width="160" />
<TableColumn @bind-Field="context.Column7" Fixed="false" Width="160" />
<TableColumn @bind-Field="context.Column8" Fixed="true" Width="160" />
<TableColumn @bind-Field="context.Column9" Fixed="true" Width="160" />

```

**Closed** 2024-03-18 06:28 UTC
Labels: bug
