### ISSUE TITLE
adding right icon to Multiselect

### ISSUE THREAD

**Issue by eramosr16** [dotnetcore/BootstrapBlazor#3623] opened 2024-06-04 22:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

MultiSelect should render a right icon like the regular Select.

### Expected Behavior

MultiSelect should render a right icon like the Select, this would help to keep consistency across all components and show the user that it needs to click to see available options.

**Comment by ArgoZhang** [comment] 2024-06-05 04:14
@eramosr16 hi could you take a look at #3556 

I think this is a duplicate of it.

**Closed** 2024-06-05 06:16 UTC
Labels: duplicate
